name: Containerize INO file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run docker file  
      working-directory: ${{runner.working-directory}}
      run: sudo ./build.sh
 
