name: Containerize INO file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run docker file  
      working-directory: ${{runner.working-directory}}
      run: |
            sudo sudo apt-get install openjdk-11-jdk
            sudo apt-get install openjre-11
            sudo docker pull tombenke/darduino:latest
            sudo chmod +x docker.sh
            sudo ./docker.sh
 
