name: Containerize INO file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env display
      shell: sh
      run: setenv DISPLAY :0.0
      
    - name: Run docker file  
      working-directory: ${{runner.working-directory}}
      shell: bash
      run: |
            sudo sudo apt-get install openjdk-11-jdk
            sudo apt install openjdk-11-jre
            sudo docker pull tombenke/darduino:latest
            sudo apt autoremove 
            sudo chmod +x docker.sh
            sudo ./docker.sh
 
